Spring
raphaelolu/starterProject pull request #6
Opened 2020-03-18 15:33 UTC by raphaelolu

2020-03-18 16:04 UTC, petermcneil requested changes
Okay a few changes to be made here.

Some of them are just cleaning up what you have, such as the folders you don't need etc. 

And some is my fault for not being clear about what is needed, I will try to make the next few tickets more detailed and clear.

2020-03-18 16:04 UTC, petermcneil commented on .gitignore
> +gs-rest-service/
We don't need this, and add `.idea`

2020-03-18 16:04 UTC, petermcneil commented on Domain/src/main/java/starterProject/domain/Doors.java
> +    private int newmkfkl;
Java typically uses camelCase for variables like this, could you convert these to that? We use it across our products, it would be good to get into this now.

`doornumbers` -> `doorNumbers`

2020-03-18 16:04 UTC, petermcneil commented on Domain/src/main/java/starterProject/domain/Engine.java
> +    private int Cylinders;
camelCase

2020-03-18 16:04 UTC, petermcneil commented on Domain/src/main/java/starterProject/domain/Transmission.java
>      private Boolean Automatic;
CamelCase

2020-03-18 16:04 UTC, petermcneil commented on Domain/src/test/java/starterProject/domain/CarTest.java
> +
Empty car test, get rid or fill it out

2020-03-18 16:04 UTC, petermcneil commented on api/.gitignore
> +
this seems to be a copied file. get rid

2020-03-18 16:04 UTC, petermcneil commented on api/mvnw
> +# Licensed to the Apache Software Foundation (ASF) under one
don't need this

2020-03-18 16:04 UTC, petermcneil commented on api/.gitignore
> +
infact get rid of `api`

2020-03-18 16:04 UTC, petermcneil commented on frontEnd/build.gradle
> +    testCompile group: 'junit', name: 'junit', version: '4.12'
get rid of this, we already have junit in the root level `build.gradle`

2020-03-18 16:04 UTC, petermcneil commented on build.gradle
> +        implementation 'com.google.code.gson:gson:2.8.6'
why is gson added?

2020-03-18 16:04 UTC, petermcneil commented on frontEnd/build.gradle
> +    implementation 'org.codehaus.groovy:groovy'
why is groovy added?

2020-03-18 16:04 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/Controller.java
> +        return new representation( String.format(template, name));
we should make this simpler. Just have this method return 
```
{
   "status" : "OK"
}
```

2020-03-18 16:04 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/representation.java
> +public class representation {
Java Classes always should start with a capital as a convention.

But this one isn't needed so get rid.

2020-03-18 16:04 UTC, petermcneil commented on gradle.properties
> +log4j = 2.11.2
you should move all the gradle versions into this file

2020-03-18 16:04 UTC, petermcneil commented on frontEnd/build.gradle
> +    id 'groovy'
similar to below, groovy isn't used here

2020-03-19 14:35 UTC, raphaelolu commented on gradle.properties
> +log4j = 2.11.2
do are you referring to the ones currently in build.gradle?

2020-03-19 14:42 UTC, petermcneil commented on gradle.properties
> +log4j = 2.11.2
Yep, so for example grab the lombok one out of the `build.gradle` and add it here like `lombok = 1.18.12`, and the new line for lombok should be `         compileOnly "org.projectlombok:lombok:$lombok"`

2020-03-19 15:14 UTC, raphaelolu commented on gradle.properties
> +log4j = 2.11.2
is that the same for ones like   testCompileOnly 'org.projectlombok:lombok:1.18.12'

2020-03-19 17:11 UTC, petermcneil requested changes

2020-03-19 17:11 UTC, petermcneil commented on frontEnd/build.gradle
> +    id 'groovy'
still not sure why groovy is used? can give me an update on that?

2020-03-19 17:11 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/Application.java
> +       List<Car> garage =  App.createCar();
why is this called here?

2020-03-19 17:11 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/CarController.java
> +    public String getCars(@RequestParam() List car ) {
this isn't part of this ticket. we are only doing the status endpoint. see #6

2020-03-19 17:11 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/CarController.java
> +        String jsonCarList = new Gson().toJson(carList );
Don't need to do that. 

Use this instead.
https://www.dineshonjava.com/using-consumes-and-produces-to/

2020-03-19 17:11 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/CarModel.java
> +public class CarModel {
don't need this, just yet

2020-03-19 17:11 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/Controller.java
> +public class Controller
This should be renamed to something more clear like `StatusController`

2020-03-19 17:11 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/Create.java
> +public class Create {
don't need this

2020-03-19 17:11 UTC, petermcneil commented on build.gradle
> +        implementation "com.google.code.gson:gson:$gson"
remove this gson

2020-03-19 17:11 UTC, petermcneil commented on frontEnd/src/main/java/olumofe/raphael/frontEnd/Application.java
> +        System.out.println("HELLLO");
don't need this either

2020-03-19 17:11 UTC, petermcneil commented on api/.gitignore
> +HELP.md
still need to get rid of this

2020-03-19 17:11 UTC, petermcneil commented on Domain/src/main/java/starterProject/App.java
> +        ArrayList<Car> objectList = new ArrayList<>();
this should be you can use `var` or `List<Car>` instead of `ArrayList<Car>`

2020-03-19 17:11 UTC, petermcneil commented on .gitignore
> +.idea
You will have to do this command.

https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

2020-03-20 15:52 UTC, petermcneil approved these changes

2020-03-20 15:52 UTC, merged